### ISSUE TITLE
Oak returns malformed Json for scan-ap

### ISSUE THREAD

**Issue by DarkLotus** [digistump/OakSoftAP#2]
ScapAP app is failing due to Error parsing the json, a comma is missing in the array.
Example output below.

{
    "scans": [{
        "ssid": "belkin.743c",
        "rssi": -47,
        "sec": 0,
        "ch": 2,
        "mdr": 0
    } {
        "ssid": "bob",
        "rssi": -47,
        "sec": 0,
        "ch": 5,
        "mdr": 0
    }]
}

**Comment by DarkLotus** [comment]
and the fix is line 39540 of softap-browser.js
var json = JSON.parse(dat.toString().replace("}{","},{"));

**Comment by DarkLotus** [comment]
and the next issue is "Must provide claim code string as first parameter"

**Comment by DarkLotus** [comment]
and the fix for that is line 210 sap.setClaimCode(claim_code, claim_callback);
replace with
            if(claim_code === "")
                claim_callback(false, {"r":0});
            else
                sap.setClaimCode(claim_code, claim_callback);

Both fixes in my fork

**Comment by DarkLotus** [comment]
Next issue is device is connected to wifi now, but particle dont have any devices listed. Debugging the claim post message now, appears that the device_ids array is empty, but its a bit of a nightmare with all this minified code.

**Comment by digistump** [comment]
@DarkLotus - you are tearing through this! JSON fix is awesome, I've been chasing that issue the last two days (it has some corner cases where it does or doesn't appear, but your fix should squash it without breaking anything.

claim code fix made me realize that this repo must be one commit behind - I'm not at home (see my comment here as to why: https://www.kickstarter.com/projects/digistump/oak-by-digistump-wi-fi-for-all-things-arduino-comp/comments) - so I don't have the current local for that, but your fix looks like what I remember doing as well.

Can't honestly remember the next one - particle testing was limited until today, so that's probably a real bug - I'll get the none minified stuff up ASAP

Many many thanks for all your help on all of this!!!

**Comment by DarkLotus** [comment]
no probs, i think my "fix" broke the claims process somewhere along the line. Im reading up on the particle api now to try and get my head around it.

Also hope all is well, peoples projects can wait family is more important!

**Comment by DarkLotus** [comment]
oak reboots and connects to wifi as far as i can see. i think the firmware update doesnt happen though as it's still v1 and system-version is file not found.

**Comment by digistump** [comment]
Yes - the firmware file isn't on the server yet, so the update doesn't
happen, it gets the 404 and reboots back to the config server image.

**Comment by DarkLotus** [comment]
okay awesome :) looks like we're all working for now then minus the issues above.

**Comment by digistump** [comment]
awesome - thanks! just got back home (5am here) gonna get some rest and
then start in on the final round before pushing it live - thanks again for
all the help!

**Comment by DarkLotus** [comment]
proper fix for the malformed JSON is .split("}{").join("},{") instead of a replace, as replace only fixes it for the first.

**Comment by digistump** [comment]
Closing - thank you again! Please reopen/create new if you see more issues

Thanks!
