### ISSUE TITLE
Firmware update

### ISSUE THREAD

**Issue by haakonnessjoen** [digistump/OakSoftAP#3]
Hi,

I have tried before, and after the release of the BETA firmware.

I have two Oaks, and one of them I tried before thebeta firmware, and I have tried beta firmware with both of them.

The problem is that they do not seem to download the firmware correctly. When I use the updater, I do se that it reboots, and the 1s 50% duty cycle blinking stops for a bit, starts again, stops, and starts.. and then it starts to blink "rapidly" as the documentation says. But only for a whole second. Then it goes back to the steady blinking again.

And my particle account has no devices registered. I have checked with the oak tool. Also, the config.html page seems to request /v1/devices from particle.io while waiting for the device to come up. But it gets a 404 back. Before the beta version, It got access denied instead.

Am I the only one having problems adding the oak's to the cloud?

**Comment by digistump** [comment]
@haakonnessjoen - when did you try - as in what days? 

Currently firmware upgrades are disabled while we address some issues we discovered with OSX/Linux64 - this is noted on the install docs - and would result in the behavior you described.

In addition if you tried before we announced the firmware was up for download then it would have done exactly as you described since it would not be able to download the upgrade image.

If you tried to upgrade on Saturday then there could be an issue - but otherwise it mostly is just that the firmware was not available and that would produce these results. Please let me know if this was on Saturday (Pacific Time) or not.

Thanks!

**Comment by haakonnessjoen** [comment]
I am actually not sure if it was saturday or sunday. The days melt together. But I saw the "firmware upgrades are disabled" title today, and I am pretty sure I did not see this. Since I read the docs carefully to see what has changed now that the beta was out (since, I got the mail about it).

But to be honest, I am not completely sure. So please do not use any of your time on this, if the disabled firmware should behave like I said.

I will just wait until you resolve the problems, and try again.

**Comment by digistump** [comment]
Sounds good - for the record I think there are some issues related to it not downloading on every try, but it is hard to decipher those until the firmware is up long enough for everyone to be sure that wasn't the cause. Please do reopen if this persists when we re-enable the updates.

Thanks!
